### PR TITLE
Integrate Dagger support

### LINKED ISSUE #20: Integrate with Dagger 2
Add dagger 2 for dependency injection. I'd like to send a pr for this soon

### PR DESCRIPTION
**Pull request by AkshayChordiya**
Implements Dagger 2 support with `ViewModel`

Continued implementation of #21 and resolves #20

### CODE REVIEW

**Comment by AkshayChordiya** [comment]
I'd love your review if it's possible @Ezike

**Comment by Ezike** [comment]
I've added a review

**Comment by Ezike** [comment]
I've reviewed

**Comment by AkshayChordiya** [comment]
Thanks @Ezike

**Pull request merged**
