### PR TITLE
feat: Integrate with dagger 2

### PR DESCRIPTION
**Pull request by Ezike**
resolves:#20

adds dagger integration to the project

### CODE REVIEW

**Comment by AkshayChordiya** [comment]
I tested the PR and it wasn't building due to few issues with `ViewModel` and Kotlin version [v1.3.30] hence I'm closing this PR and created another PR based upon this #22

**Comment by Ezike** [comment]
Okay. I've been trying to resolve the problem with injecting the viewmodel into the viewmodelprovider.factory class

Like you said, seems to be an issue with version

**Comment by AkshayChordiya** [comment]
Yeah it was 2 fold problem.

1. Needed to add few more things for `ViewModel
2. Conflict with Dagger and Kotlin v1.3.30 [https://github.com/google/dagger/issues/1478]

**Comment by Ezike** [comment]
Okay. I saw that the issue was raised on the Dagger repo

**Comment by Ezike** [comment]
I saw your invite to collaborate on the repo but the link seems broken

**Pull request closed without merging**
